create database mydatabase;

select * from customer
limit 10;

-- what is the total revenue generated by male vs female customers

select 
gender,
sum(purchase_amount) as revenue
from customer
group by gender; 

-- which customer used a discount but still spend more than the average purchase amount

select
customer_id,
purchase_amount
from customer
where discount_applied ='Yes' and purchase_amount > (select avg (purchase_amount) from customer);

-- which are the top 5 products with highest average review rating

select
item_purchased, round(avg(review_rating),2) as average_product_rating
from customer
group by item_purchased
order by average_product_rating desc
limit 5;

-- compare the average purchase amount between standard and experess shipping

select 
shipping_type,
round(avg(purchase_amount),2) as avg_purchase_amount
from customer
where shipping_type in('Express','Standard')
group by shipping_type;

-- do subscribed customers spend more? compare average spend and total revenue between subscibers and non-subscribers.alter

select
subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as average_spend,
sum(purchase_amount) as total_revenue
from customer
group by subscription_status;

-- which 5 products have the highest percentage of purchase with discount applied

select 
item_purchased,
round(sum(case when discount_applied='yes' then 1 else 0 end)/count(*)*100,2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- segment customers into New, Returning, Loyal based on their total number of previous purchases, and show the count of each segment

select
	case when previous_purchases <2 then 'New'
    when previous_purchases between 2 and 10  then 'Returning'
    else 'Loyal' end as customer_type,
    count(*) as number_of_customer
from customer
group by customer_type;

-- what are the top 3 most purchased product within each category.

with item_count as (
select category,item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_count
where item_rank<=3;

-- are customers who are repeat buyers (more than five previous purchases) also likely to sbscribe

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases >5
group by subscription_status;

-- what is the revenue contribution of each age group

select age_group,
sum(purchase_amount) as revenue
from customer
group by age_group
order by revenue desc;
